#!/usr/bin/env python3
"""Interactive configuration script that generates a .env file.

Run this once to set up your RainHue environment.  The resulting .env file
is loaded automatically by the config module at runtime.
"""

import os
import sys


def _prompt(label, default=None, required=True):
    """Prompt the user for a value, with optional default."""
    suffix = f" [{default}]" if default else ""
    value = input(f"{label}{suffix}: ").strip()
    if not value and default is not None:
        return default
    if not value and required:
        print(f"  Error: {label} is required.")
        return _prompt(label, default, required)
    return value


def _prompt_float(label, default=None):
    """Prompt for a value that must be a valid float."""
    raw = _prompt(label, default=str(default) if default is not None else None)
    try:
        float(raw)
        return raw
    except ValueError:
        print(f"  Error: '{raw}' is not a valid number.")
        return _prompt_float(label, default)


def main():
    print("=" * 50)
    print("  RainHue Configuration")
    print("=" * 50)
    print()
    print("This script will create a .env file with your")
    print("Philips Hue and location settings.")
    print()

    hue_uri = _prompt("Hue remote API URI", default="https://api.meethue.com/")
    hue_username = _prompt("Hue bridge username")
    hue_token = _prompt("Hue OAuth token")
    hue_lamp = _prompt("Name of the Hue lamp to control", default="Desk Lamp")
    print()
    latitude = _prompt_float("Latitude (e.g. 52.52)")
    longitude = _prompt_float("Longitude (e.g. 13.41)")

    env_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), ".env")

    if os.path.exists(env_path):
        overwrite = input(
            f"\n.env already exists at {env_path}. Overwrite? [y/N]: "
        ).strip().lower()
        if overwrite not in ("y", "yes"):
            print("Aborted. Existing .env was not modified.")
            sys.exit(0)

    with open(env_path, "w") as f:
        f.write("# RainHue configuration — generated by createconfig.py\n")
        f.write("\n")
        f.write("# Philips Hue bridge settings\n")
        f.write(f"HUE_URI={hue_uri}\n")
        f.write(f"HUE_USERNAME={hue_username}\n")
        f.write(f"HUE_TOKEN={hue_token}\n")
        f.write(f"HUE_LAMP={hue_lamp}\n")
        f.write("\n")
        f.write("# GPS coordinates for weather forecast\n")
        f.write(f"LATITUDE={latitude}\n")
        f.write(f"LONGITUDE={longitude}\n")

    print(f"\nConfiguration saved to {env_path}")
    print("You can edit this file manually at any time.")


if __name__ == "__main__":
    main()
