#!/usr/bin/env python3
"""Interactive configuration script that generates a .env file for RainHue v2.

Run this once after completing the Hue OAuth pairing flow (see README.md).
The resulting .env is loaded automatically at runtime.
"""

import os
import sys


def _prompt(label, default=None, required=True):
    suffix = f" [{default}]" if default else ""
    value = input(f"{label}{suffix}: ").strip()
    if not value and default is not None:
        return default
    if not value and required:
        print(f"  Error: {label} is required.")
        return _prompt(label, default, required)
    return value


def _prompt_float(label, default=None):
    raw = _prompt(label, default=str(default) if default is not None else None)
    try:
        float(raw)
        return raw
    except ValueError:
        print(f"  Error: '{raw}' is not a valid number.")
        return _prompt_float(label, default)


def main():
    print("=" * 50)
    print("  RainHue v2 Configuration")
    print("=" * 50)
    print()
    print("Complete the Hue OAuth pairing flow first (see README.md),")
    print("then paste the resulting values here.")
    print()

    hue_client_id = _prompt("Hue OAuth client id")
    hue_client_secret = _prompt("Hue OAuth client secret")
    hue_token = _prompt("Hue access token (HUE_TOKEN)")
    hue_refresh = _prompt("Hue refresh token (HUE_REFRESH_TOKEN)")
    hue_username = _prompt("Hue bridge username (whitelist user)")
    hue_lamp = _prompt("Name of the Hue lamp to control", default="Desk Lamp")
    print()
    latitude = _prompt_float("Latitude", default="59.33")
    longitude = _prompt_float("Longitude", default="18.07")

    env_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), ".env")

    if os.path.exists(env_path):
        overwrite = input(f"\n.env already exists at {env_path}. Overwrite? [y/N]: ").strip().lower()
        if overwrite not in ("y", "yes"):
            print("Aborted. Existing .env was not modified.")
            sys.exit(0)

    with open(env_path, "w") as f:
        f.write("# RainHue configuration — generated by createconfig.py\n\n")
        f.write(f"HUE_CLIENT_ID={hue_client_id}\n")
        f.write(f"HUE_CLIENT_SECRET={hue_client_secret}\n")
        f.write(f"HUE_TOKEN={hue_token}\n")
        f.write(f"HUE_REFRESH_TOKEN={hue_refresh}\n")
        f.write(f"HUE_USERNAME={hue_username}\n")
        f.write("HUE_URI=https://api.meethue.com\n")
        f.write(f"HUE_LAMP={hue_lamp}\n\n")
        f.write(f"LATITUDE={latitude}\n")
        f.write(f"LONGITUDE={longitude}\n")
        f.write("TIMEZONE=Europe/Stockholm\n")

    print(f"\nConfiguration saved to {env_path}")


if __name__ == "__main__":
    main()
