localIP = raw_input("Input your local IP address to Philips Hue Bridge: ")
lampName = raw_input("Input name of your selected Philips Hue lamp: ")
apiKey = raw_input("Input your Darksky API key: ")
latitude = raw_input("Input your latitude: ")
longitude = raw_input("Input your longitude: ")

with open("localconfig.py", "w") as f:
    f.write("#!/usr/bin/env python\n")
    f.write("\n")
    f.write("#IP of bridge\n")
    f.write("bridge = '" + localIP + "'\n")
    f.write("\n")
    f.write("#Name of lamp that will change colour\n")
    f.write("selectedLamp = '" + lampName + "'\n")
    f.write("\n")
    f.write("#Dark sky API key\n")
    f.write("API_KEY = '" + apiKey + "'\n")
    f.write("\n")
    f.write("#GPS position for forecast\n")
    f.write("coordinates = ['" + latitude + "', '" + longitude + "']\n")
    f.write("\n")
    f.write("#Set lamp colors [brightness, hue, saturation]\nrainColor = [120, 45000, 254]\nsnowColor = [120, 25000, 254]\ndefaultColor = [254, 10000, 0]")
